### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by Allan6966** [pedsm/liveCup#1]
Hello!

I've a problem. I have a dedicated virtual machine for the dashboard but I'm unable to load anything :(
Does a specific configuration is needed?

Server version: Apache/2.4.25 (Debian)

PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.27-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies

php7.0-gd + php7.0-json + php7.0-mysql + php7.0-curl + php7.0-mbstring
php7.0-intl + php7.0-mcrypt + php-imagick + php7.0-xml + php7.0-zip

No error in apache log.

https://cdm.sogcap.allan6966.fr/

Best regards.

Allan.

**Comment by Allan6966** [comment]
Okaaaaaay, I'm dumb. I have to set dist/ as virtualhost home folder.
You can delete this "issue" :|

**Comment by pedsm** [comment]
Thanks for the input but I will re-organise the repo in such a way that you will be able to serve root. For compatibility reasons, I will leave `/dist` for the next couple of commits but Ideally, it would all be served at the root. This was only the case because this was a rushed project.
