### ISSUE TITLE
trying to integrate this ui with Django

### ISSUE THREAD

**Issue by riceluxs1t** [pedsm/liveCup#2]
Hi,

I am very new to React and am having some trouble integrating this ui with my backend Django App that does some WorldCup prediction (https://github.com/riceluxs1t/EloSoccerPrediction).

Would you mind telling me details on 
1. which webpack configuration does this use?
2) what is ant-design?

I am trying to set it up following this post http://v1k45.com/blog/modern-django-part-1-setting-up-django-and-react/ but your react app seems to have been setup differently.

**Comment by riceluxs1t** [comment]
Hi,

I actually got it all to work and my website is now up at http://ec2-13-125-192-62.ap-northeast-2.compute.amazonaws.com/

**Comment by riceluxs1t** [comment]
I actually got it all to work at http://ec2-13-125-192-62.ap-northeast-2.compute.amazonaws.com/ and my github at https://github.com/riceluxs1t/EloSoccerPrediction. 

I mentioned that I borrowed the prototype ui idea from your repo. Thanks in advance!

**Comment by pedsm** [comment]
Hey glad you liked the UI, sorry I didn't get back to you sooner as I am currently traveling abroad so my internet access is limited but do let me know if you need anything else.
